# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Pinball Map Blog
url:   http://blog.pinballmap.com
author:
  name:    Pinball Map Blog # For copyright notice and ATOM feeds
  email:   master.cob@gmail.com # Exception emails will go here, and it is used in ATOM feeds

  # If you want to use the google_oauth2 (Google OpenID Connect) OmniAuth strategy to login to the admin area,
  # google_oauth2_email should match the email of your OpenID Connect identity
  google_oauth2_email: gratzer@gmail.com
